name: Fly Deploy
on: [push]
jobs:
  deploy:
    environment: "deployment"
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Check out copy of repository
      - uses: actions/checkout@v2
      # Run fly deploy
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
